apiVersion: v1
kind: Secret
metadata:
  name: order-saga-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.postgres.writeUrl | quote }}
  DATABASE_URL_READ: {{ .Values.postgres.readUrl | quote }}
